# Use the official Node.js image as a base
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Set npm configurations and install dependencies
RUN npm config set registry https://registry.npmjs.org/ && \
    npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 20000 && \
    npm config set fetch-retry-maxtimeout 120000 && \
    npm install --no-optional --verbose

# Copy the rest of your application code
COPY . .

# Build the application
RUN npm run build

# Expose the port that your app runs on
EXPOSE 3000

# Start the application with the host flag
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3000"]
