# Use the official Node.js image as a base
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./ 

# Install dependencies using npm ci
RUN npm install --no-optional --verbose

# Copy the rest of your application code
COPY . . 

# Expose the port that your backend runs on
EXPOSE 5000

# Start the backend application
CMD ["npm", "start"]
