# Use Node.js 14 as the base image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available) to install dependencies
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy the backend source code
COPY . .

# Copy the .env file
COPY .env .  
#This ensures the .env file is copie

# Expose the backend port
EXPOSE 5000

# Start the application
CMD ["npm", "start"]
